### ISSUE TITLE
problem with height

### ISSUE THREAD

**Issue by marcoswmv** [sh-khashimov/RESegmentedControl#1]
I am using your control on a project and something's wrong.
The log on Xcode is giving back some error description regarding to the height. I'll copy and paste it here.

**The behavior of the UICollectionViewFlowLayout is not defined because:
the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x103ffa1d0>, and it is attached to <UICollectionView: 0x104d5ea00; frame = (-187.5 -24.5; 375 49); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x28294c300>; animations = { bounds.origin=<CASpringAnimation: 0x282604ec0>; UIPacingAnimationForAnimatorsKey=<CABasicAnimation: 0x282605020>; bounds.size=<CASpringAnimation: 0x282604de0>; }; layer = <CALayer: 0x28263b120>; contentOffset: {0, 0}; contentSize: {0, 0}; adjustedContentInset: {0, 0, 0, 0}; layout: <UICollectionViewFlowLayout: 0x103ffa1d0>; dataSource: <RESegmentedControl.RESegmentedControl: 0x103ff6840; baseClass = UIControl; frame = (0 156; 375 49); autoresize = RM+BM; layer = <CALayer: 0x28263bd60>>>.
Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.**

Could you tell what this can be?

**Comment by sh-khashimov** [comment]
I am aware of this warning. I will try to fix it in a future release. 
However, this warning does not affect functionality. What exactly doesn’t work for you?

**Comment by marcoswmv** [comment]
Well, it doesn't affect the functionality. I just was surprised that I was using it normally without any log messages and now they just started appearing. And also I think if you got any type of messages like this something might be wrong, so that's why I tried to look for an answer. I'll wait for it then

**Comment by sh-khashimov** [comment]
Thank you for using RESegmentedControl. 
I fixed that problem in version 0.2.1, please update to the latest version.
If you still have any problems, please let me know.
