### ISSUE TITLE
Error when building packages

### ISSUE THREAD

**Issue by lilidotshi** [sh-khashimov/RESegmentedControl#11]
The file UIView+Gradient is getting an error because it seems to be missing an `import UIKit`

**Comment by sh-khashimov** [comment]
Sorry about that. Fixed.

**Comment by lilidotshi** [comment]
Awesome,  thank you! Could you cut a new release with the fix too?

**Comment by sh-khashimov** [comment]
You're welcome!
Version 0.5.4 should fix that problem.
