### ISSUE TITLE
Freezes on device, works on simulator

### ISSUE THREAD

**Issue by mrgerh** [sh-khashimov/RESegmentedControl#2]
RESegmentedControl freezes on device in method `super.layoutSubviews()` utilising 100% CPU.
Just run Example app on the device and you will see.
In simulator it works fine. Checked on latest iOS 13.5.1 on iPhone 8 and iPhone XS.
Commenting out `super.layoutSubviews()` solves an issue, but I think it is not the best solution...

**Comment by sh-khashimov** [comment]
It seems something changed on iOS 13.2.
https://developer.apple.com/forums/thread/124022
I will investigate the problem tomorrow.

**Comment by sh-khashimov** [comment]
It should be fixed now on 0.3.1, please re-open the issue if the bug still exists.

**Comment by mrgerh** [comment]
Great, it works now. Thanks a lot!
