### ISSUE TITLE
Change Text on a particular segment?

### ISSUE THREAD

**Issue by kfound** [sh-khashimov/RESegmentedControl#4]
I'd like to be able to change text on a particular segment once the whole control is setup. My use case is that I want to show the count of items related to that segment in the text of the segment. I realize `SegmentModel` is a struct so you can't change the data within it.  If that could change to a class then I could simply update the text displayed.  Barring that - Maybe a new method like `segment.replaceItem(item :SegmentModel, atIndex: Int)` and it could replace the item there?

**Comment by sh-khashimov** [comment]
`replaceItem` added in version 0.4.0, please let me know if something working wrong.

**Comment by kfound** [comment]
Fast response! Thanks! I haven't downloaded and tested it yet... Do you know if this will maintain the selected segment? I tried to do a replace like this: 

    UIView.performWithoutAnimation {
            let chartModel = SegmentModel(title: newTitle, imageName: "file-tiny")
            self.lineSegmentControl.removeItem(atIndex: myIndex)
            self.lineSegmentControl.addItem(chartModel, atIndex: myIndex)
    }

and it loses the selected segment. If I try and reselect the segment in this code (which is called as a result of selecting a segment) I obviously get into an infinite loop.  I'll try to download the new version and see if it works as expected.

**Comment by kfound** [comment]
Just downloaded and tested out the replaceItem ... looks like it's working great and keeping the selected segment. No need to `performWithoutAnimation`.

Thanks so much!

**Comment by sh-khashimov** [comment]
It's my pleasure! 
Please re-open the issue if you found bugs related to the `replaceItem` API. 
I will try my best to fix as fast as possible :)
