### ISSUE TITLE
Segments with text and no icon aren't centered

### ISSUE THREAD

**Issue by kfound** [sh-khashimov/RESegmentedControl#5]
I'm using the `BootstapPreset` with a bit of customization on fonts and colors. Two of my segments have icons, and the third one doesn't.  The third segment has the text offset to the right as if there was an image, but there isn't.  The first two segments with images and text are properly centered across all those components in the segment. 

![image](https://user-images.githubusercontent.com/43919489/90341065-4a7af900-dfb1-11ea-8738-a6c03e5fe929.png)

I had downloaded the code from github to run the Example project (on version 0.3.2), and I see the same issue there so I suspect it's not just a problem with the fact that one of my segments doesn't have an icon.

![image](https://user-images.githubusercontent.com/43919489/90341177-3be11180-dfb2-11ea-98fb-fd5bc53c9ea0.png)

Here's how I'm creating my SegmentModels:

            let chartModel = SegmentModel(title: "Charts", imageName: "file-tiny")
            let projectModel = SegmentModel(title: "Weaving Projects", imageName: "project-tiny")
            let bothModel = SegmentModel(title: "Both")
            let models = [chartModel, projectModel, bothModel]

I don't think the rest of the preset code matters, but here it is just in case:

            let textColor: UIColor = UIColor.init(named: "flippedText") ?? .lightText
            let selectedTextColor = UIColor.white 
            var preset = BootstapPreset(backgroundColor: .clear,
                                        selectedBackgroundColor: secondaryHeaderColor,
                                        textColor: textColor,
                                        selectedTextColor: selectedTextColor)
            
            let itemStyle = SegmentItemStyle(backgroundColor: .clear,
                                             textColor: .lightGray,
                                             tintColor: .lightGray,
                                             selectedTextColor: selectedTextColor,
                                             selectedTintColor: selectedTextColor)
            
            preset.segmentItemStyle = itemStyle
            preset.textFont = textFont
            preset.selectedTextFont = boldFont
            preset.imageRenderMode = .alwaysTemplate
            preset.segmentSpacing = 20
            preset.selectedSegmentItemCornerRadius = 5
            preset.selectedSegmentItemShadow = SegmentItemShadowStyle(color: UIColor.black.cgColor, opacity: 0.3, offset: .zero, radius: 5, path: nil)

            reSegmentControl.configure(segmentItems: models, preset: preset, selectedIndex: 0)

Thanks for taking a look!

**Comment by sh-khashimov** [comment]
Thank you for being informed. I have fixed and released a new version. Please, let me know if it still not working properly.

**Comment by kfound** [comment]
Updated with the fix and it's looking great. Thanks for the quick fix.
