### ISSUE TITLE
SPM Crash due to 'Could not load NIB in bundle: 'NSBundle  (loaded)' with name 'SegmentCollectionViewCell''

### ISSUE THREAD

**Issue by cerupcat** [sh-khashimov/RESegmentedControl#7]
When using SPM, it looks like it's unable to find some of the assets and therefore crashes.

`*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle (loaded)' with name 'SegmentCollectionViewCell`

**Comment by sh-khashimov** [comment]
should work now, update to 0.5.1 version.

**Comment by cerupcat** [comment]
Thanks for the quick response!
